### ISSUE TITLE
error..

### ISSUE THREAD

**Issue by jpk0305** [bugsounet/EXT-Detector#147]
Checking all dependencies...
Updating package...
Missing package: libmagic-dev
Missing package: libatlas-base-dev
Missing package: sox
Missing package: libsox-fmt-all
Installing missing package...
기존:1 http://archive.raspberrypi.com/debian bookworm InRelease                
받기:2 http://raspbian.raspberrypi.com/raspbian bookworm InRelease [15.0 kB]   
패키지 목록을 읽는 중입니다... 완료     
W: http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Release file for http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease is not valid yet (invalid for another 15시간 26분 18초). Updates for this repository will not be applied.
npm ERR! code 255
npm ERR! path /home/pi/MagicMirror/modules/EXT-Detector
npm ERR! command failed
npm ERR! command sh -c installer/preinstall.sh -d 'libmagic-dev libatlas-base-dev sox libsox-fmt-all build-essential'

npm ERR! A complete log of this run can be found in: /home/pi/.npm/_logs/2024-07-02T07_01_37_668Z-debug-0.log

**Comment by bugsounet** [comment]
Hi, it's not really an `EXT-Detector` issue

Actually, your system is not able to any system update/install command

So, check your `adp` config of your system and correct this part (in Error):
`E: Release file for http://raspbian.raspberrypi.com/raspbian/dists/bookworm/InRelease is not valid yet (invalid for another 15시간 26분 18초). Updates for this repository will not be applied.`
